# NumPy Assessment

#### Create a numpy array called ‘height in inches’ from a list 10 of numbers: [66, 68, 71, 64, 61, 74, 64, 65, 70, 71]. Create a new array called ‘height_in_feet’ and make its values equal to the values in the first array divided by 12.

In [1]:
import numpy as np

In [20]:
height_in_inches = np.array([66, 68, 71, 64, 61, 74, 64, 65, 70, 71], dtype='int')
divisor = 12
height_in_feet = height_in_inches/divisor

print(height_in_feet)

[5.5        5.66666667 5.91666667 5.33333333 5.08333333 6.16666667
 5.33333333 5.41666667 5.83333333 5.91666667]


#### Create a 5x5 array of zeros.

In [25]:
a = np.zeros([5,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### Create an array of random floating point numbers between 0 and 100.

In [106]:
b = np.random.randint(low=0.0, high=100.0, size=(10))
print(b)

[70 66 28 71 61 19 92 67 83 72]


#### Create an array of numbers from 0 to 75 in increments of 5.

In [75]:
c = np.arange(0,75,5)
print(c)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70]
